<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.scx</groupId>
        <artifactId>scx-parent</artifactId>
        <version>1</version>
        <relativePath/>
    </parent>

    <artifactId>labs</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>ray-tracing</module>
        <module>stackcall</module>
    </modules>

    <dependencies>

        <dependency>
            <groupId>dev.scx</groupId>
            <artifactId>scx-function</artifactId>
            <version>${scx-function.version}</version>
        </dependency>

    </dependencies>

    <properties>

        <scx-function.version>0.10.0</scx-function.version>

    </properties>

</project>
